/**
 * DDL for the Better Auth tables inside the `authStore` actor's SQLite.
 *
 * **Edit this file and `./schema.ts` together.** `./schema.ts` describes the
 * shape Drizzle queries against; this file is what actually exists in the
 * database. A drift between them surfaces as `no such column`, which is a much
 * worse error to debug than it looks, because the failing query is generated.
 *
 * ---
 *
 * ### Spec note — deviation from docs/06 §4.3
 *
 * docs/06 §4.3 says the `authStore` tables come from "migrations generated by
 * `drizzle-kit` and committed". This file runs hand-written idempotent DDL from
 * the actor's `onMigrate` hook instead. What changed and why:
 *
 *  1. `rivetkit/db/drizzle`'s `migrations` option wants a `{ journal, migrations }`
 *     bundle produced by `drizzle-kit generate` and *imported into the server
 *     bundle*. Wiring that up needs a second `drizzle.config.ts` (the one at the
 *     repo root belongs to the legacy SvelteKit/Postgres scaffold that docs/06
 *     §4.1 retires) plus a codegen step in CI. That is a lot of apparatus for
 *     five tables that Better Auth's own schema pins for us.
 *  2. `onMigrate` is invoked by RivetKit **inside a migration savepoint**
 *     (`withMigrationSavepoint` in `rivetkit/src/db/drizzle.ts`), so these
 *     statements are already atomic as a group — which is the property the
 *     migration runner would have provided.
 *  3. Every statement is `IF NOT EXISTS`, so the hook is safe to run on every
 *     actor wake, including the repeated wakes a serverless migration causes.
 *
 * The cost is that this file cannot express a *destructive* change (a dropped
 * column, a retyped column). When one is needed, switch to `drizzle-kit`
 * migrations at that point — the schema in `./schema.ts` is already the input
 * `drizzle-kit` needs, so nothing here has to be re-derived.
 *
 * ---
 *
 * Column types follow the Drizzle modes in `./schema.ts`: `date` →
 * `INTEGER` epoch-milliseconds, `boolean` → `INTEGER` 0/1.
 */

/**
 * The minimum surface `runAuthMigrations` needs from a Drizzle client. Declared
 * structurally so this module does not depend on RivetKit's generic
 * `DrizzleDatabase<TSchema>` and stays trivially unit-testable against a fake.
 */
export interface AuthMigrationRunner {
	execute<TRow extends Record<string, unknown> = Record<string, unknown>>(
		query: string,
		...args: unknown[]
	): Promise<TRow[]>;
}

/**
 * Statements are executed in array order, one per `execute()` call — the SQLite
 * driver behind `c.db` runs a single statement per call, so a semicolon-joined
 * blob would silently execute only its first statement.
 */
const STATEMENTS: readonly string[] = [
	// Foreign keys are off by default in SQLite. The `ON DELETE CASCADE` clauses
	// below are inert without this, which would leave orphaned sessions behind a
	// deleted user.
	'PRAGMA foreign_keys = ON',

	`CREATE TABLE IF NOT EXISTS "user" (
		"id" TEXT PRIMARY KEY NOT NULL,
		"name" TEXT NOT NULL,
		"email" TEXT NOT NULL UNIQUE,
		"emailVerified" INTEGER NOT NULL DEFAULT 0,
		"image" TEXT,
		"createdAt" INTEGER NOT NULL,
		"updatedAt" INTEGER NOT NULL
	)`,

	`CREATE TABLE IF NOT EXISTS "session" (
		"id" TEXT PRIMARY KEY NOT NULL,
		"expiresAt" INTEGER NOT NULL,
		"token" TEXT NOT NULL UNIQUE,
		"createdAt" INTEGER NOT NULL,
		"updatedAt" INTEGER NOT NULL,
		"ipAddress" TEXT,
		"userAgent" TEXT,
		"userId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE
	)`,
	'CREATE INDEX IF NOT EXISTS "session_userId_idx" ON "session" ("userId")',

	`CREATE TABLE IF NOT EXISTS "account" (
		"id" TEXT PRIMARY KEY NOT NULL,
		"accountId" TEXT NOT NULL,
		"providerId" TEXT NOT NULL,
		"userId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
		"accessToken" TEXT,
		"refreshToken" TEXT,
		"idToken" TEXT,
		"accessTokenExpiresAt" INTEGER,
		"refreshTokenExpiresAt" INTEGER,
		"scope" TEXT,
		"password" TEXT,
		"createdAt" INTEGER NOT NULL,
		"updatedAt" INTEGER NOT NULL
	)`,
	'CREATE INDEX IF NOT EXISTS "account_userId_idx" ON "account" ("userId")',

	`CREATE TABLE IF NOT EXISTS "verification" (
		"id" TEXT PRIMARY KEY NOT NULL,
		"identifier" TEXT NOT NULL,
		"value" TEXT NOT NULL,
		"expiresAt" INTEGER NOT NULL,
		"createdAt" INTEGER NOT NULL,
		"updatedAt" INTEGER NOT NULL
	)`,
	'CREATE INDEX IF NOT EXISTS "verification_identifier_idx" ON "verification" ("identifier")',

	`CREATE TABLE IF NOT EXISTS "rateLimit" (
		"id" TEXT PRIMARY KEY NOT NULL,
		"key" TEXT NOT NULL UNIQUE,
		"count" INTEGER NOT NULL,
		"lastRequest" INTEGER NOT NULL
	)`
];

/**
 * Create every Better Auth table that does not already exist.
 *
 * Idempotent, and cheap enough to run on every actor wake: seven `IF NOT
 * EXISTS` statements against a local SQLite file.
 */
export async function runAuthMigrations(db: AuthMigrationRunner): Promise<void> {
	for (const statement of STATEMENTS) {
		await db.execute(statement);
	}
}
